version: "3.8"
services:
  frontend-node:
    build:
      context: docker/node
    volumes:
      - ./app:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
    ports:
      - "8080:3000"
      - "3000:3000"
  frontend-node-cli:
    build:
      context: docker/node
    volumes:
      - ./app:/app